### ISSUE TITLE
Upgrade pravega client version to 0.9.1

### ISSUE THREAD

**Issue by vangork** [pravega/spark-connectors#112]
upgrade pravega client version 0.9.1-2777.26b543c-SNAPSHOT

**Comment by claudiofahey** [comment]
I don't think we want to upgrade the master branch to 0.10.0 yet. Per our compat matrix at https://github.com/pravega/spark-connectors#compatibility-matrix, master should contain Pravega 0.9.x and the latest release is 0.9.0. Is there a particular reason to upgrade to a snapshot version?

**Comment by vangork** [comment]
> I don't think we want to upgrade the master branch to 0.10.0 yet. Per our compat matrix at https://github.com/pravega/spark-connectors#compatibility-matrix, master should contain Pravega 0.9.x and the latest release is 0.9.0. Is there a particular reason to upgrade to a snapshot version?

The request is from Brian and seems to be oringinally from QE. @claudiofahey

**Comment by crazyzhou** [comment]
Yes, QEs are starting longevity test against Pravega 0.9.1 that requires a 0.9.1 spark connector, though we have no changes since 0.9.0 for connector itself, but there are some changes from the pravega client side that would be better to include in the test. That's why we need this issue.

Pravega master branch has already been into 0.10 snapshot version, the connector master branch needs to follow up. For 0.9.1, we should keep it in `r0.9` branch

**Comment by claudiofahey** [comment]
Ok thanks for explaining. In that case, we should:
1. Create branch r0.9-spark3.0 for Pravega 0.9.1.
2. Update the master branch to Pravega 0.10.
3. Update the compatibility matrix in README.md of the master branch.

**Comment by crazyzhou** [comment]
> Ok thanks for explaining. In that case, we should:
> 
> 1. Create branch r0.9-spark3.0 for Pravega 0.9.1.
> 2. Update the master branch to Pravega 0.10.
> 3. Update the compatibility matrix in README.md of the master branch.

I think for 1, `r0.9` branch is already for spark 3.0, so no need to create a new branch unless we plan to support spark 3.1 for spark 0.9

For 2 and 3, we will do in #116 together

**Comment by crazyzhou** [comment]
And there is another small task which needs to cherrypick this change into `r0.9-spark2.4` to fix the Spark 2.4 connector. Once I have done this, I will close this issue.

**Comment by crazyzhou** [comment]
Closed via #115 and cherry-pick
