### ISSUE TITLE
Upgrade Pravega 0.10 to the latest snapshot version

### ISSUE THREAD

**Issue by thekingofcity** [pravega/spark-connectors#116]
**Problem description**

Upgrade Pravega 0.10 to the latest commit

**Problem location**

`gradle.properties`

Suggestions for an improvement

**Comment by claudiofahey** [comment]
I don't think we want to upgrade the master branch to 0.10.0 yet. Per our compat matrix at https://github.com/pravega/spark-connectors#compatibility-matrix, master should contain Pravega 0.9.x and the latest release is 0.9.0. Is there a particular reason to upgrade to a snapshot version?

**Comment by crazyzhou** [comment]
Created `r0.10-spark2.4` branch to track spark 2.4 connector
