### ISSUE TITLE
Set scaling policy

### ISSUE THREAD

**Issue by fpj** [pravega/spark-connectors#2]
*Summary*

Set scaling policy in `PravegaSourceProvider`. See TODO in the `createStreamMethod`.

*Detail*

Pravega enables three different types of scaling policies: fixed, event rate, byte rate. See:

https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/stream/ScalingPolicy.java

The fixed policy disables auto-scaling, whereas the other two enable and configure auto-scaling. This issue is about enabling the scaling policy to be configurable. A user should be able to enable auto-scaling and configure it accordingly when running this connector with a Spark job. To be able to choose the scaling policy and configure it, the connector configuration need to expose corresponding parameters to configure the stream just like the other parameters that it currently uses.

Note that this is stream is being created for an optional writer to save the data.

**Comment by claudiofahey** [comment]
Closed via #63 .
