### ISSUE TITLE
pravega-client: impact of grpc-netty upgrade

### ISSUE THREAD

**Issue by derekm** [pravega/spark-connectors#65]
I'm looking to upgrade grpc-netty in pravega-client, so that pravega-client can be brought into environments using newer versions of Netty. Details here: https://github.com/pravega/pravega/pull/5016

Spark 2.4.x uses a mix of Netty versions, including 3.9.9.

Would upgrading grpc-netty to latest in pravega-client negatively impact spark-connectors?

**Comment by claudiofahey** [comment]
Spark connector has already been upgraded to Pravega 0.9 with no GRPC issues.
