### ISSUE TITLE
Drop travis and enable github actions for CI pipeline

### ISSUE THREAD

**Issue by crazyzhou** [pravega/spark-connectors#87]
travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com
As Pravega has already transitioned to use github actions in pravega/pravega#5563
We need to do this change as well

**Comment by claudiofahey** [comment]
The GitHub Action build that was just merged into master is failing a test. Please investigate.

**Comment by thekingofcity** [comment]
Should be fixed in #109 `Spark fail to bind the address in the tests`.

**Comment by claudiofahey** [comment]
Looks like the test passes and the publish to http://oss.jfrog.org/jfrog-dependencies/io/pravega/pravega-connectors-spark-3.0_2.12/0.9.0-1.59d8f01-SNAPSHOT/ works. However, the commit count in the artifact is 1 but it should be higher. Please make this update: https://github.com/pravega/flink-connectors/blob/master/.github/workflows/build.yml#L20

**Comment by thekingofcity** [comment]
The wrong commit count will be fixed in #111 `Wrong commit count number of the artifact name`.

**Comment by claudiofahey** [comment]
The repo http://oss.jfrog.org/jfrog-dependencies/io/pravega/pravega-connectors-spark-3.0_2.12/ has a link 0.9.0/-> 0.9.0-1.59d8f01-SNAPSHOT/. This may confuse users. Can we remove this invalid link? It may have been published accidently.

**Comment by crazyzhou** [comment]
You may misinterpret that, the `0.9.0` is the official 0.9 version we release, it does not have any timestamp infomation because it's just synchronized from sonatype maven central, and you can click into that 0.9.0 and see that is the official release artifacts. The `->` may be confusing, but it's not a link to the bottom line `0.9.0-1.59d8f01-SNAPSHOT`.

**Comment by claudiofahey** [comment]
Thanks Brian. I did misinterpret that.
